### ISSUE TITLE
data-i18n="text_movement_direction" があると，document.getElementById('text_movement_direction")がnullになる

### ISSUE THREAD

**Issue by TetsuakiBaba** [TetsuakiBaba/commentable#21]
@kurohune538 目視でOKだったんで，マージしたんですが動作させてみたら，タイトルの症状でてました．該当箇所はここね
https://github.com/TetsuakiBaba/commentable/blob/4f3cb5132e957f4748f7257e677e9c97e2e42017/public/sketch.js#L327

そちらの手元でもjsコンソールでボタン押すとエラーがでるのでわかるかなと思います．
なんか思い当たる節あるでしょうか？

**Comment by kurohune538** [comment]
おっと、確認してみます

**Comment by kurohune538** [comment]
僕の手元ではコンソール特に何も出ていないのですが、どのボタンを押したときでしょうか？
再現したいのでもう少し具体的な状況知りたいです

**Comment by TetsuakiBaba** [comment]
1. cd commentable/
2. node server.js
3. ブラウザで http://localhost を開く
4. ボタンをどれか押すと添付画像のエラーがコンソールい表示される
![スクリーンショット 2024-07-05 13 18 57](https://github.com/TetsuakiBaba/commentable/assets/1846131/72f27d63-9529-40f0-ad8c-8fadb288641d)
@kurohune538

**Comment by TetsuakiBaba** [comment]
解決しました．
https://github.com/TetsuakiBaba/commentable/blob/4f3cb5132e957f4748f7257e677e9c97e2e42017/public/index.html#L187

このelementでdata-i18nのattributeを入れてしまうと翻訳処理でappendされている select elementが全部消えてしまいます．正しくは，文字だけの要素を<sapn>でくくり，そこに data-i18n のattributeを設定しなければなりません．

**Comment by TetsuakiBaba** [comment]
[b2ac179](https://github.com/TetsuakiBaba/commentable/commit/b2ac17930df3759f301101d9a18b524ef2eab683)

**Comment by kurohune538** [comment]
なるほどです、修正ありがとうございます！
